package com.example.dianzicheng.domain

import java.util.Calendar
import kotlin.math.max

object BodyAlgorithm {
    fun calculate(
        weightKg: Double,
        impedanceOhm: Double,
        sex: Sex,
        heightCm: Double,
        birthDateEpochMs: Long
    ): BodyMeasurement {
        val heightM = heightCm / 100.0
        val bmi = weightKg / (heightM * heightM)
        val age = calculateAge(birthDateEpochMs)

        val sexOffset = if (sex == Sex.MALE) -10.8 else 0.0

        val fallbackFat = 1.20 * bmi + 0.23 * age + sexOffset - 5.4
        val biaFat = if (sex == Sex.MALE) {
            0.18 * bmi + 0.012 * age + 0.018 * impedanceOhm - 3.2
        } else {
            0.26 * bmi + 0.011 * age + 0.020 * impedanceOhm - 2.5
        }

        val fat = (if (impedanceOhm > 0) biaFat else fallbackFat).coerceIn(5.0, 55.0)

        val water = (69.7 - fat * 0.55).coerceIn(35.0, 75.0)
        val bone = (weightKg * (if (sex == Sex.MALE) 0.047 else 0.040)).coerceIn(1.5, 5.5)
        val protein = (16.0 + (water - 50.0) * 0.12).coerceIn(10.0, 24.0)
        val muscle = max(weightKg * (1 - fat / 100.0) - bone, 0.0)

        return BodyMeasurement(
            id = "", // Generated by repository
            measuredAtEpochMs = System.currentTimeMillis(),
            weightKg = weightKg,
            impedanceOhm = impedanceOhm,
            bmi = bmi,
            bodyFatPct = fat,
            muscleKg = muscle,
            waterPct = water,
            proteinPct = protein,
            boneMassKg = bone,
            memberId = null,
            memberNameSnapshot = null
        )
    }

    private fun calculateAge(birthDateEpochMs: Long): Int {
        val today = Calendar.getInstance()
        val birthDate = Calendar.getInstance().apply {
            timeInMillis = birthDateEpochMs
        }
        var age = today.get(Calendar.YEAR) - birthDate.get(Calendar.YEAR)
        if (today.get(Calendar.DAY_OF_YEAR) < birthDate.get(Calendar.DAY_OF_YEAR)) {
            age--
        }
        return age.coerceIn(1, 120)
    }
}
